### ISSUE TITLE
panic: runtime error: index out of range in gaad.window_grouping

### ISSUE THREAD

**Issue by gy741** [Comcast/gaad#10]
Hello.

I found a  index out of range bug in gaad.

Please confirm.

Thanks.

reproduce code:
```
package gaad

import (
	"testing"
)

func TestFuzzCrashers(t *testing.T) {

	var crashers = []string{
		"\xff\xf10\x850",
	}

	for _, f := range crashers {
		ParseADTS([]byte(f))
	}
}

```

Crash Log:
```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 17 [running]:
testing.tRunner.func1(0xc42004d520)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x5337a0, 0x5fbe10)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/Comcast/gaad.window_grouping(0xc420073720, 0x400000c)
	/home/karas/go/src/github.com/Comcast/gaad/aacwindowgrouping.go:151 +0xe30
github.com/Comcast/gaad.(*ADTS).ics_info(0xc42004d5f0, 0x0, 0x4f4e00, 0x5e9b00, 0xc4200b52d0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1114 +0x2b9
github.com/Comcast/gaad.(*ADTS).individual_channel_stream(0xc42004d5f0, 0x0, 0x0, 0x5e9b00, 0xc4200b52c0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1398 +0x3ad
github.com/Comcast/gaad.(*ADTS).coupling_channel_element(0xc42004d5f0, 0x3, 0x2, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1204 +0x300
github.com/Comcast/gaad.(*ADTS).raw_data_block(0xc42004d5f0, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1006 +0x8b3
github.com/Comcast/gaad.(*ADTS).adts_frame(0xc42004d5f0, 0xc420019800, 0x5)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:796 +0x91
github.com/Comcast/gaad.ParseADTS(0xc4200b52a0, 0x5, 0x8, 0xc4200b52a0, 0x5, 0x8)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:773 +0xbe
github.com/Comcast/gaad.TestFuzzCrashers(0xc42004d520)
	/home/karas/go/src/github.com/Comcast/gaad/fuzzer_test.go:14 +0x90
testing.tRunner(0xc42004d520, 0x5647e0)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/Comcast/gaad	0.011s
```

**Comment by BlakeOrth** [comment]
Fixed in https://github.com/Comcast/gaad/commit/d0d0b0de01c2058cf7be491e07e08bb439e250f8

Closing.
