### ISSUE TITLE
panic: runtime error: len out of range in (*BitReader).ReadBitsToByteArray

### ISSUE THREAD

**Issue by gy741** [Comcast/gaad#7]
Hello.

I found a len out of range bug in gaad.

Please confirm.

Thanks.

reproduce code:

```
package gaad

import (
	"testing"
)

func TestFuzzCrashers(t *testing.T) {

	var crashers = []string{
			"\xff\xf100000\xc3\xdc",
	}

	for _, f := range crashers {
		ParseADTS([]byte(f))
	}
}
```

Crash Log:
```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 17 [running]:
testing.tRunner.func1(0xc42004d520)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x5337a0, 0xc4200b52e0)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/Comcast/gaad/bitreader.(*BitReader).ReadBitsToByteArray(0xc420019800, 0xfffffffffffffff9, 0x5e9b00, 0xc4200b52d0, 0xc4200b52c0, 0xc420027cf0, 0x4f4ef6)
	/home/karas/go/src/github.com/Comcast/gaad/bitreader/bitreader.go:129 +0x72
github.com/Comcast/gaad.(*ADTS).sbr_extension_data(0xc42004d5f0, 0x1, 0x100, 0x0, 0x0, 0xc420019800, 0x40ef01)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1913 +0x1b1
github.com/Comcast/gaad.(*ADTS).extension_payload(0xc42004d5f0, 0x1, 0x4f0000, 0x0, 0x0, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1740 +0x3d4
github.com/Comcast/gaad.(*ADTS).fill_element(0xc42004d5f0, 0x0, 0x6, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1293 +0xbf
github.com/Comcast/gaad.(*ADTS).raw_data_block(0xc42004d5f0, 0x0, 0x0)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:1020 +0x269
github.com/Comcast/gaad.(*ADTS).adts_frame(0xc42004d5f0, 0xc420019800, 0x9)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:796 +0x91
github.com/Comcast/gaad.ParseADTS(0xc4200b52a0, 0x9, 0x10, 0xc4200b52a0, 0x9, 0x10)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:773 +0xbe
github.com/Comcast/gaad.TestFuzzCrashers(0xc42004d520)
	/home/karas/go/src/github.com/Comcast/gaad/fuzzer_test.go:14 +0x90
testing.tRunner(0xc42004d520, 0x5647e0)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/Comcast/gaad	0.010s
```

**Comment by LimitlessEarth** [comment]
We have likely fixed this with #17 or #18 ! We are unable to reproduce.
