### ISSUE TITLE
panic: runtime error: index out of range in gaad.(*ADTS).adts_header_error_check

### ISSUE THREAD

**Issue by gy741** [Comcast/gaad#9]
Hello.

I found a  index out of range bug in gaad.

Please confirm.

Thanks.

reproduce code:
```
package gaad

import (
	"testing"
)

func TestFuzzCrashers(t *testing.T) {

	var crashers = []string{
		"\xff\xf00000\x010",
	}

	for _, f := range crashers {
		ParseADTS([]byte(f))
	}
}

```

Crash Log:
```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 17 [running]:
testing.tRunner.func1(0xc42004d380)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x5337a0, 0x5fbe10)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/Comcast/gaad.(*ADTS).adts_header_error_check(0xc42004d450)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:895 +0xf8
github.com/Comcast/gaad.(*ADTS).adts_frame(0xc42004d450, 0xc420019800, 0x8)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:801 +0xd9
github.com/Comcast/gaad.ParseADTS(0xc4200b52a0, 0x8, 0x8, 0xc4200b52a0, 0x8, 0x8)
	/home/karas/go/src/github.com/Comcast/gaad/aacparser.go:773 +0xbe
github.com/Comcast/gaad.TestFuzzCrashers(0xc42004d380)
	/home/karas/go/src/github.com/Comcast/gaad/fuzzer_test.go:14 +0x90
testing.tRunner(0xc42004d380, 0x5647e0)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/Comcast/gaad	0.009s
```

**Comment by BlakeOrth** [comment]
Fixed in https://github.com/Comcast/gaad/commit/d0d0b0de01c2058cf7be491e07e08bb439e250f8

Closing.
